

### Soit la victime souhaite déposer plainte  

#### Soit les faits sont récents < 48h :  

**= urgence médicale et « judiciaire »**  

Coduite à tenir: 

- En l’absence de **contact** préalable **avec la police**, appeler le numéro unique de l’état-major de la Préfecture de police au **01 87 27 66 36** (ou le commissariat d’arrondissement en journée)  
    - avec les informations : nom, prénom, DDN de la victime, lieu des faits et type de faits déclarés  

**La police contactera rapidement les UMJ qui prendra en charge la victime sur réquisition judiciaire** (examen sur rdv)  

- Contact avec le **médecin légiste référent à l’UMJ (numéro à ne pas communiquer aux victimes !!)**  
- (NB : préciser que vous n’avez pas la trithérapie !!)  
    - Journée : **01 42 34 78 08** (médecin réfèrent) ou 01 42 34 87 00 (Accueil consultation)  
    - Nuit : **01 42 34 78 08** (médecin légiste de garde) ou 01 42 34 84 46 (IDE de garde)  

- **Conseils à donner à la victime :**  
    - **ne pas se laver** avant l’examen UMJ (si possible)  
    - si la victime a déjà pris une douche, lui remettre une enveloppe kraft pour qu’elle **mette de côté les sous-vetements portés** lors ou suite aux faits,  
- **Ne pas faire d’examen** gynécologique/anal (**sauf si nécessité de soins** : prise en charge spécialisée)  
- Eviter l’examen corporel (contamination ADN) ; **Si examen : utiliser des gants**  
- **Si suspicion de soumission chimique : contacter l’UMJ 01 42 34 78 08** +/- faire bilan à garder au frigo et en informer le médecin UMJ  
- **Prélèvements à titre conservatoire :**  
    - 2 tubes de sang sur EDTA  
    - 3 tubes à bouchon rouge 7 ml d’urines  
    - 2 tubes à bouchon vert hépariné  

**bilan conservatoire pourra être remis dans un 2e temps aux autorités : TOUJOURS SUR REQUISITON**  

- Remettre le compte rendu de passage à la victime (mentionnant les éventuels traitements reçus...)  

#### Soit les faits ont entre > 48h et < 1 sem et ne s’est pas lavée  

**= intérêt médico-légal**  

- Appel Médecin référent **UMJ 01 42 34 78 08** pour **définir si urgence ou non**  
- **Si suspicion de soumission chimique : contacter l’UMJ 01 42 34 78 08** +/- faire bilan à garder au frigo et en informer le médecin UMJ  
- **Prélèvements à titre conservatoire :**  
    - 2 tubes de sang sur EDTA  
    - 3 tubes à bouchon rouge 7 ml d’urines  
    - 2 tubes à bouchon vert hépariné  

**bilan conservatoire pourra être remis dans un 2e temps aux autorités : TOUJOURS SUR REQUISITON**  

- **si pas d’urgence** : conseiller d’aller **déposer plainte au commissariat de secteur** qui prendra rdv à l’UMJ  
- conseils à donner à la victime : possibilité de lui remettre une enveloppe kraft pour qu’elle mette de côté les sous-vetements portés lors ou suite aux faits,  

#### soit les faits ont >48h et s’est lavée  

**= aucune urgence**  

- **Conseil de dépôt de plainte dans commissariat** de son quartier qui prendra le rdv à l’UMJ à l’issue de l’audition.  
- Conseils à donner à la victime : possibilité de lui remettre une enveloppe kraft pour qu’elle mette de côté les sous-vêtements portés lors ou suite aux faits,  

### Soit la victime ne souhaite pas déposer plainte  

l’urgence = urgence médicale :  

- **PEC AES et grossesse** => **adresser au SAU Cochin pour prise en charge selon protocole ++++**  
- **Aucune indication à faire** examen gynécologique/anal (sauf si nécessité de soins) **ni prélèvements locaux.**  
- Possibilité de conseil de conserver sous-vêtement dans une enveloppe papier, surtout si hésitation sur dépôt de plainte  
- **Si examen réalisé : remettre un certificat descriptif** (prudence dans la rédaction du certificat, **rester objectif**) souvent **violence physique associée à décrire**  
- **Informer la victime qu’elle peut changer d’avis concernant la plainte** (et le noter dans le dossier...), possibilité de dépôt de plainte **à tout moment**  
- Proposer prise en charge adaptée si nécessaire (sociale, psychologique.. associations.)  
- S’assurer que la victime ne reparte pas seule  
